Repository BidderOwn/BidderOwn_BE, pull requests merged in 2023-05, with the labels that each got.

#2 [#1] 초기 설정
  src/main/java/site/bidderown/server/HelloController.java
Labels: documentation

#12 Refactoring/11 users to member
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/base/security/CustomOAuth2UserService.java
  src/main/java/site/bidderown/server/base/security/SecurityConfig.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/member/controller/dto/MemberResponse.java
  src/main/java/site/bidderown/server/bounded_context/member/entity/Member.java
  src/main/java/site/bidderown/server/bounded_context/member/repository/MemberRepository.java
  src/main/java/site/bidderown/server/bounded_context/member/service/MemberService.java
  src/main/java/site/bidderown/server/bounded_context/users/controller/dto/UsersResponse.java
  src/main/java/site/bidderown/server/bounded_context/users/repository/UsersRepository.java
  src/main/java/site/bidderown/server/bounded_context/users/service/UsersService.java
  src/main/resources/templates/usr/item/home.html
Labels: Refactoring

#13 [#10] 채팅 도메인 초기 설정
  .DS_Store
  src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatController.java
  src/main/java/site/bidderown/server/bounded_context/chat/entity/Chat.java
  src/main/java/site/bidderown/server/bounded_context/chat/repository/ChatRepository.java
  src/main/java/site/bidderown/server/bounded_context/chat/service/ChatService.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/entity/ChatRoom.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/repository/ChatRoomRepository.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
Labels: Feature

#15 상품 등록
  build.gradle
  src/main/java/site/bidderown/server/base/base_entity/BaseEntity.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Image.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/application-secret.yml.txt
  src/main/resources/application.yml
  src/test/java/site/bidderown/server/bounded_context/item/Controller/ItemControllerTest.java
Labels: Feature

#21 [#20] 채팅방 상대방 유저 이름 가져오는 코드 오류 해결
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomResponse.java
Labels: BugFix

#22 [#19] chat room test
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomRequest.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomResponse.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/entity/ChatRoom.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
  src/main/java/site/bidderown/server/bounded_context/member/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomServiceTest.java
Labels: Test

#26 Refactor : SuperBuilder를 제거합니다
  src/main/java/site/bidderown/server/base/base_entity/BaseEntity.java
  src/main/java/site/bidderown/server/bounded_context/chat/entity/Chat.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/entity/ChatRoom.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/member/entity/Member.java
Labels: Refactoring

#29 [#28] 채팅방 컨트롤러를 리팩토링합니다.
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
Labels: Refactoring
