Repository BidderOwn/BidderOwn_BE, pull requests merged in 2023-06, with the labels that each got.

#32 [#31] UserDetailService 추가
  src/main/java/site/bidderown/server/base/security/CustomOAuth2UserService.java
  src/main/java/site/bidderown/server/base/security/CustomUserDetailsService.java
  src/main/java/site/bidderown/server/bounded_context/member/entity/Member.java
Labels: BugFix

#33 [#30] 채팅방 Controller 테스트
  build.gradle
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomRequest.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/test/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomControllerTest.java
  src/test/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomServiceTest.java
Labels: Test

#37 [#24] 상품 CRUD 리팩터링
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Image.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/test/java/site/bidderown/server/bounded_context/item/Controller/ItemControllerTest.java
Labels: Refactoring

#38 [#35] socket configure and vue
  src/main/java/site/bidderown/server/base/websocket/WebSocketConfig.java
  src/main/resources/templates/header.html
  src/main/resources/templates/usr/chat/list.html
  src/main/resources/templates/usr/item/home.html
Labels: Feature

#39 [#36] 채팅 저장 기능 구현
  src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatController.java
  src/main/java/site/bidderown/server/bounded_context/chat/controller/dto/ChatRequest.java
  src/main/java/site/bidderown/server/bounded_context/chat/controller/dto/ChatResponse.java
  src/main/java/site/bidderown/server/bounded_context/chat/service/ChatService.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
Labels: Feature

#42 [#40] chatroom-controller 테스트 코드
  src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
  src/test/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomControllerTest.java
  src/test/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomServiceTest.java
Labels: BugFix

#46 [#41] 상품 전체 리팩토링
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Image.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/ItemStatus.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/test/java/site/bidderown/server/bounded_context/item/Controller/ItemControllerTest.java
Labels: Refactoring

#47 [#43] 입찰 도메인에 대한 초기 작업을 진행합니다.
  src/main/java/site/bidderown/server/bounded_context/bid/controller/BidController.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidRequest.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
  src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
  src/main/java/site/bidderown/server/bounded_context/bid/entity/BidResult.java
  src/main/java/site/bidderown/server/bounded_context/bid/repository/BidRepository.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
Labels: Feature

#48 [#45] 리팩토링-메서드-이름
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/BidController.java
  src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
  src/main/java/site/bidderown/server/bounded_context/bid/entity/BidResult.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
  src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatController.java
  src/main/java/site/bidderown/server/bounded_context/chat/service/ChatService.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomRequest.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomResponse.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/java/site/bidderown/server/bounded_context/member/controller/dto/MemberDetail.java
  src/main/java/site/bidderown/server/bounded_context/member/service/MemberService.java
  src/test/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomControllerTest.java
  src/test/java/site/bidderown/server/bounded_context/item/Controller/ItemControllerTest.java
Labels: Refactoring

#51 feature: chat-room-기능-완료
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/bounded_context/HomeController.java
  src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatController.java
  src/main/java/site/bidderown/server/bounded_context/chat/controller/dto/ChatRequest.java
  src/main/java/site/bidderown/server/bounded_context/chat/controller/dto/ChatResponse.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
  src/main/resources/templates/header.html
  src/main/resources/templates/usr/chat/list.html
  src/main/resources/templates/usr/item/home.html
Labels: Feature

#54 [#49] 입찰 컨트롤러 테스트 작성
  src/main/java/site/bidderown/server/bounded_context/bid/controller/BidController.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidRequest.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
  src/test/java/site/bidderown/server/bounded_context/bid/controller/BidControllerTest.java
Labels: Test

#59 [#58] Spring batch config
  build.gradle
  src/main/java/site/bidderown/server/ServerApplication.java
  src/main/java/site/bidderown/server/batch/BatchScheduler.java
  src/main/java/site/bidderown/server/batch/hello/config/HelloJobConfiguration.java
  src/main/java/site/bidderown/server/batch/hello/step/HelloStepTasklet.java
  src/main/resources/application.yml
Labels: Setting

#61 [#57] 댓글 CRUD
  src/main/java/site/bidderown/server/bounded_context/comment/controller/CommentController.java
  src/main/java/site/bidderown/server/bounded_context/comment/controller/dto/CommentDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/comment/controller/dto/CommentRequest.java
  src/main/java/site/bidderown/server/bounded_context/comment/controller/dto/CommentResponse.java
  src/main/java/site/bidderown/server/bounded_context/comment/entity/Comment.java
  src/main/java/site/bidderown/server/bounded_context/comment/repository/CommentRepository.java
  src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemUpdateDto.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/images/item/item_1685952401063.webp
  src/main/resources/images/item/item_1685952401074.jpeg
Labels: Feature

#63 [#60] Item 경매종료 Batch 처리
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/batch/BatchScheduler.java
  src/main/java/site/bidderown/server/batch/hello/config/HelloJobConfiguration.java
  src/main/java/site/bidderown/server/batch/hello/step/HelloStepTasklet.java
  src/main/java/site/bidderown/server/batch/item/config/ItemJobConfiguration.java
  src/main/java/site/bidderown/server/batch/item/listener/BidEndJobListener.java
  src/main/java/site/bidderown/server/batch/item/step/ItemStep.java
Labels: BugFix, Feature

#67 Feature : 알림 초기작업
  src/main/java/site/bidderown/server/bounded_context/notification/controller/NotificationController.java
  src/main/java/site/bidderown/server/bounded_context/notification/controller/dto/NotificationDto.java
  src/main/java/site/bidderown/server/bounded_context/notification/entity/Notification.java
  src/main/java/site/bidderown/server/bounded_context/notification/entity/NotificationType.java
  src/main/java/site/bidderown/server/bounded_context/notification/repository/NotificationRepository.java
  src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
Labels: Feature

#68 [#66] 알림 경매, 입찰건 기능 추가
  src/main/java/site/bidderown/server/ServerApplication.java
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/base/event/EventItemNotification.java
  src/main/java/site/bidderown/server/batch/item/config/ItemJobConfiguration.java
  src/main/java/site/bidderown/server/batch/item/listener/BidEndItemWriterListener.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
  src/main/java/site/bidderown/server/bounded_context/notification/controller/NotificationController.java
  src/main/java/site/bidderown/server/bounded_context/notification/entity/Notification.java
  src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
  src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
Labels: Setting, Feature

#70 [#62] 상품 입찰목록 조회
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
Labels: Refactoring

#69 [#64] feature:comment-update 기능추가
  src/main/java/site/bidderown/server/bounded_context/comment/controller/CommentController.java
  src/main/java/site/bidderown/server/bounded_context/comment/controller/dto/CommentRequest.java
  src/main/java/site/bidderown/server/bounded_context/comment/controller/dto/CommentResponse.java
  src/main/java/site/bidderown/server/bounded_context/comment/entity/Comment.java
  src/main/java/site/bidderown/server/bounded_context/comment/repository/CommentRepository.java
  src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
Labels: Feature

#74 refactoring: fetch-type-lazy로-변경
  src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
  src/main/java/site/bidderown/server/bounded_context/chat/entity/Chat.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/entity/ChatRoom.java
  src/main/java/site/bidderown/server/bounded_context/notification/entity/Notification.java
Labels: Refactoring

#77 [#72] 상품 입찰 부분 수정
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
Labels: Refactoring

#80 Feature/71 query tuning
  build.gradle
  src/main/generated/site/bidderown/server/base/base_entity/QBaseEntity.java
  src/main/generated/site/bidderown/server/bounded_context/bid/entity/QBid.java
  src/main/generated/site/bidderown/server/bounded_context/chat/entity/QChat.java
  src/main/generated/site/bidderown/server/bounded_context/chat_room/entity/QChatRoom.java
  src/main/generated/site/bidderown/server/bounded_context/comment/entity/QComment.java
  src/main/generated/site/bidderown/server/bounded_context/image/entity/QImage.java
  src/main/generated/site/bidderown/server/bounded_context/item/entity/QItem.java
  src/main/generated/site/bidderown/server/bounded_context/member/entity/QMember.java
  src/main/generated/site/bidderown/server/bounded_context/notification/entity/QNotification.java
  src/main/java/site/bidderown/server/ServerApplication.java
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/base/event/EventBidEndNotification.java
  src/main/java/site/bidderown/server/batch/BatchScheduler.java
  src/main/java/site/bidderown/server/batch/item/config/ItemJobConfiguration.java
  src/main/java/site/bidderown/server/batch/item/listener/BidEndItemWriterListener.java
  src/main/java/site/bidderown/server/batch/item/listener/BidEndJobListener.java
  src/main/java/site/bidderown/server/batch/item/step/ItemStep.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRepository.java
  src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
  src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
  src/main/resources/application.yml
Labels: Setting, Feature, Refactoring

#83 [#78] 상품 검색, 페이징
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemListResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
Labels: Feature

#82 Feature : bulkInsert도입
  src/main/generated/site/bidderown/server/bounded_context/item/entity/QItem.java
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BulkInsertBid.java
  src/main/java/site/bidderown/server/bounded_context/bid/repository/BidJdbcRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/BulkInsertItem.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemJdbcRepository.java
  src/main/java/site/bidderown/server/bounded_context/notification/controller/dto/BulkInsertNotification.java
  src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
  src/main/java/site/bidderown/server/bounded_context/notification/repository/NotificationJdbcRepository.java
Labels: Feature, Refactoring

#87 [#86] mypage ui작업 + text-color통합
  src/main/resources/templates/usr/myPage.html
  src/main/resources/templates/usr/notification/list.html
Labels: Feature

#94 initData 아이템 이미지 서버에 존재하는 파일이용하면 생성
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
  src/main/resources/images/item/banana.jpg
Labels: Feature, Refactoring

#95 [#93] home 수정
  src/main/java/site/bidderown/server/base/security/SecurityConfig.java
  src/main/java/site/bidderown/server/bounded_context/HomeController.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/BidController.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomApiController.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
  src/main/java/site/bidderown/server/bounded_context/notification/controller/NotificationController.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/controller/SocketConnectionController.java
Labels: Refactoring

#96 [#91] 입찰 단위/상품 등록 이미지
  src/main/resources/templates/usr/bid/list.html
  src/main/resources/templates/usr/item/create.html
Labels: Refactoring

#98 [#97] view단의 임시 데이터들을 실제 아이템의 이미지로 변경
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
  src/main/resources/templates/usr/item/detail.html
  src/main/resources/templates/usr/item/home.html
  src/main/resources/templates/usr/my_page.html
Labels: Feature

#99 Feature/90 socket connection
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/base/event/EventItemBidderNotification.java
  src/main/java/site/bidderown/server/base/event/EventItemSellerNotification.java
  src/main/java/site/bidderown/server/base/event/EventSocketConnection.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
  src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/java/site/bidderown/server/bounded_context/notification/controller/dto/BulkInsertNotification.java
  src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
  src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/controller/dto/SocketConnectionRequest.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/controller/dto/SocketConnectionResponse.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/entity/ConnectionType.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/event_handler/SocketConnectionEventHandler.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/service/SocketConnectionService.java
  src/main/resources/templates/header.html
  src/main/resources/templates/usr/bid/list.html
  src/main/resources/templates/usr/notification/list.html
Labels: Refactoring

#102 [#101] 경매가 종료됐거나 판매가 종료된 상품 경매종료 UI추가
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemListResponse.java
  src/main/resources/templates/usr/item/detail.html
  src/main/resources/templates/usr/item/home.html
Labels: Feature

#104 [#103] mypage 수정
  src/main/resources/templates/usr/my_page.html
Labels: Refactoring

#106 [#105] 판매완료 후 처리
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidDetails.java
  src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
  src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
  src/main/resources/templates/usr/bid/list.html
  src/main/resources/templates/usr/item/detail.html
  src/main/resources/templates/usr/item/home.html
  src/main/resources/templates/usr/my_page.html
Labels: BugFix, Feature, Refactoring

#108 [#107]공통로직 병합
  src/main/java/site/bidderown/server/base/event/EventSoldOutNotification.java
  src/main/java/site/bidderown/server/base/util/TimeUtils.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidDetails.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemResponse.java
Labels: Refactoring

#110 [#109]만료시간 반올림
  src/main/java/site/bidderown/server/base/util/TimeUtils.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
Labels: Feature

#111 Feature/89 chat
  src/main/java/site/bidderown/server/batch/BatchScheduler.java
  src/main/java/site/bidderown/server/bounded_context/HomeController.java
  src/main/java/site/bidderown/server/bounded_context/bid/repository/BidCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatController.java
  src/main/java/site/bidderown/server/bounded_context/chat/controller/dto/ChatMessageRequest.java
  src/main/java/site/bidderown/server/bounded_context/chat/controller/dto/ChatNotificationRequest.java
  src/main/java/site/bidderown/server/bounded_context/chat/repository/ChatRepository.java
  src/main/java/site/bidderown/server/bounded_context/chat/service/ChatService.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomApiController.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomDetail.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomRequest.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomResponse.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/entity/ChatRoom.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/repository/ChatRoomCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/repository/ChatRoomRepository.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/repository/dto/ChatRoomInfo.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
  src/main/java/site/bidderown/server/bounded_context/member/controller/MemberController.java
  src/main/java/site/bidderown/server/bounded_context/member/entity/Member.java
  src/main/java/site/bidderown/server/bounded_context/member/service/MemberService.java
  src/main/java/site/bidderown/server/bounded_context/notification/repository/NotificationRepository.java
  src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/controller/SocketConnectionController.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/entity/ConnectionType.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/repository/SocketConnectionRepository.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/service/SocketConnectionService.java
  src/main/resources/templates/header.html
  src/main/resources/templates/usr/chat/list.html
  src/main/resources/templates/usr/item/detail.html
  src/test/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomControllerTest.java
Labels: Feature, Refactoring

#116 [#100] 예외처리
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/base/exception/GlobalExceptionHandler.java
  src/main/java/site/bidderown/server/base/util/ImageUtils.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
Labels: Refactoring

#118 [#117] 채팅방 위 상품 정보 상품 상세보기 페이지로 연결
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomDetail.java
  src/main/resources/templates/usr/chat/list.html
Labels: Feature

#120 [#119] 아이템 상세페이지 버튼 수정
  src/main/resources/templates/usr/item/detail.html
Labels: Feature

#123 [#122] form-login UI 수정
  src/main/resources/templates/usr/form_login.html
Labels: Refactoring

#125 상세정보 페이지 경매 종료일 때 버튼 수정
  src/main/resources/templates/usr/bid/list.html
Labels: Feature

#127 Feature/126 bid button
  src/main/resources/templates/usr/bid/list.html
Labels: BugFix

#128 refactoring: batch-time
  src/main/java/site/bidderown/server/base/util/TimeUtils.java
  src/main/java/site/bidderown/server/batch/item/config/ItemJobConfiguration.java
Labels: Refactoring

#131 refactoring: ready-to-merge
  src/main/java/site/bidderown/server/batch/BatchScheduler.java
  src/main/resources/application-secret.yml.txt
  src/main/resources/application.yml
  src/main/resources/templates/usr/item/home.html
Labels: BugFix, Setting, Refactoring

#134 [#133] event to step
  .DS_Store
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/base/event/EventBidEndNotification.java
  src/main/java/site/bidderown/server/batch/BatchScheduler.java
  src/main/java/site/bidderown/server/batch/item/config/ItemJobConfiguration.java
  src/main/java/site/bidderown/server/batch/item/listener/BidEndNotificationWriterListener.java
  src/main/java/site/bidderown/server/bounded_context/bid/repository/BidCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/bid/repository/BidRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
  src/main/java/site/bidderown/server/bounded_context/notification/repository/dto/BidEndNotification.java
  src/main/java/site/bidderown/server/bounded_context/notification/repository/dto/JdbcNotification.java
  src/main/resources/application.yml
Labels: Feature

#137 [#136] 입찰 리팩토링
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomResponse.java
  src/main/resources/templates/usr/chat/list.html
Labels: Refactoring

#139 Refactoring/138 notification refactor
  src/main/java/site/bidderown/server/bounded_context/notification/controller/NotificationController.java
  src/main/java/site/bidderown/server/bounded_context/notification/controller/dto/NotificationResponse.java
  src/main/resources/templates/usr/notification/list.html
Labels: BugFix, Refactoring

#145 [#141] 채팅 controller 분리
  src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatApiController.java
  src/main/java/site/bidderown/server/bounded_context/chat/controller/ChatController.java
  src/main/resources/templates/usr/chat/list.html
Labels: BugFix, Refactoring

#146 Feature/115 item controller
  README.md
  build.gradle
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/batch/BatchScheduler.java
  src/main/java/site/bidderown/server/bounded_context/comment/controller/CommentController.java
  src/main/java/site/bidderown/server/bounded_context/comment/entity/Comment.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemSimpleResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemUpdate.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemJdbcRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/dto/BulkInsertItem.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/java/site/bidderown/server/bounded_context/member/controller/MemberController.java
  src/main/java/site/bidderown/server/bounded_context/member/service/MemberService.java
  src/main/java/site/bidderown/server/bounded_context/notification/repository/NotificationJdbcRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/templates/import.html
  src/main/resources/templates/usr/item/create.html
  src/main/resources/templates/usr/item/detail.html
  src/main/resources/templates/usr/item/home.html
Labels: BugFix, Setting, Feature, Refactoring

#152 [#150] 상품 리팩토링
  src/main/generated/site/bidderown/server/bounded_context/item/entity/QItem.java
  src/main/java/site/bidderown/server/base/event/EventSocketDisconnection.java
  src/main/java/site/bidderown/server/base/exception/ForbiddenException.java
  src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
  src/main/java/site/bidderown/server/bounded_context/comment/controller/CommentController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/event_handler/SocketConnectionEventHandler.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/repository/SocketConnectionRepository.java
  src/main/java/site/bidderown/server/bounded_context/socket_connection/service/SocketConnectionService.java
  src/main/resources/templates/usr/item/detail.html
Labels: BugFix, Test, Feature, Refactoring

#153 [#151] 입찰 삭제 기능 추가
  src/main/java/site/bidderown/server/bounded_context/bid/controller/BidApiController.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidResponse.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
  src/main/resources/templates/usr/bid/list.html
Labels: Feature

#156 [#147] 댓글 리팩토링
  src/main/java/site/bidderown/server/bounded_context/comment/controller/CommentApiController.java
  src/main/java/site/bidderown/server/bounded_context/comment/controller/CommentController.java
  src/main/java/site/bidderown/server/bounded_context/comment/entity/Comment.java
  src/main/java/site/bidderown/server/bounded_context/comment/repository/CommentCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
  src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
Labels: Feature, Refactoring

#160 Refactoring/159 global exception
  src/main/java/site/bidderown/server/base/exception/ConflictException.java
  src/main/java/site/bidderown/server/base/exception/CustomException.java
  src/main/java/site/bidderown/server/base/exception/ErrorCode.java
  src/main/java/site/bidderown/server/base/exception/ErrorResponse.java
  src/main/java/site/bidderown/server/base/exception/ForbiddenException.java
  src/main/java/site/bidderown/server/base/exception/GlobalExceptionHandler.java
  src/main/java/site/bidderown/server/base/exception/NotFoundException.java
  src/main/java/site/bidderown/server/base/exception/custom_exception/BidEndItemException.java
  src/main/java/site/bidderown/server/base/exception/custom_exception/DuflicationException.java
  src/main/java/site/bidderown/server/base/exception/custom_exception/ForbiddenException.java
  src/main/java/site/bidderown/server/base/exception/custom_exception/NotFoundException.java
  src/main/java/site/bidderown/server/base/security/CustomUserDetailsService.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomApiController.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
  src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
  src/main/java/site/bidderown/server/bounded_context/image/controller/ImageController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/java/site/bidderown/server/bounded_context/member/service/MemberService.java
  src/main/java/site/bidderown/server/bounded_context/notification/controller/NotificationController.java
  src/main/resources/templates/usr/my_page.html
Labels: Setting, Feature, Refactoring

#163 입찰 취소 예외처리
  src/main/java/site/bidderown/server/bounded_context/bid/controller/BidApiController.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
Labels: BugFix

#164 [#34] test-환경-분리
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/test/java/site/bidderown/server/bounded_context/bid/controller/BidControllerTest.java
  src/test/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomControllerTest.java
  src/test/java/site/bidderown/server/bounded_context/item/Controller/ItemControllerTest.java
Labels: Setting

#167 [#165] 알림 서비스 단위 테스트 작성
  src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
  src/test/java/site/bidderown/server/bounded_context/notification/service/NotificationServiceTest.java
Labels: Test

#172 [#171] 스프링 배치 아이템 리더 오류 해결
  src/main/java/site/bidderown/server/batch/BatchScheduler.java
  src/main/java/site/bidderown/server/batch/item/config/ItemJobConfiguration.java
Labels: BugFix

#175 판매 문구 변경, bidList itemStatus비교 String -> enum타입으로 변경
  src/main/java/site/bidderown/server/bounded_context/bid/controller/dto/BidDetails.java
  src/main/resources/templates/usr/bid/list.html
  src/main/resources/templates/usr/notification/list.html
Labels: BugFix, Refactoring

#178 [#177] 입찰 서비스 권한체크
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/bounded_context/bid/controller/BidApiController.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
Labels: Refactoring

#179 [#173] item all sort and search
  src/main/java/site/bidderown/server/base/util/ImageUtils.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemRequest.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/images/test/test.txt
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: Test

#182 [#180] 판매완료 테스트 코드
  src/main/resources/images/test/test.txt
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: Test

#183 [#176] 알림 서비스 리팩토링 및 통합 테스트 작성
  src/main/java/site/bidderown/server/bounded_context/notification/controller/dto/NewBidNotificationRequest.java
  src/main/java/site/bidderown/server/bounded_context/notification/repository/NotificationRepository.java
  src/main/java/site/bidderown/server/bounded_context/notification/service/NotificationService.java
  src/test/java/site/bidderown/server/bounded_context/notification/service/NotificationServiceTest.java
Labels: Test

#184 [#155] 입찰 서비스 테스트
  src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
  src/test/java/site/bidderown/server/bounded_context/bid/service/BidServiceTest.java
Labels: Test, Refactoring

#188 상품 테스트 추가
  src/main/resources/images/test/test.txt
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: Test

#191 [#166] 댓글 테스트
  src/main/java/site/bidderown/server/bounded_context/comment/entity/Comment.java
  src/main/java/site/bidderown/server/bounded_context/comment/repository/CommentRepository.java
  src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRepository.java
  src/test/java/site/bidderown/server/bounded_context/comment/CommentServiceTest.java
Labels: BugFix, Test, Refactoring

#189 [#187] 채팅 방 통합 테스트 작성
  src/main/java/site/bidderown/server/base/exception/ErrorCode.java
  src/main/java/site/bidderown/server/base/exception/custom_exception/SoldOutItemException.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
  src/test/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomServiceTest.java
Labels: Test, Refactoring

#196 [#194] application-rdb.yml 추가
  .gitignore
  build.gradle
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/resources/application-rdb.yml.txt
  src/main/resources/application.yml
Labels: Setting
