Repository BidderOwn/BidderOwn_BE, pull requests merged in 2023-07, with the labels that each got.

#198 [#197] 상품 리스트 쿼리 튜닝
  src/main/generated/site/bidderown/server/bounded_context/item/entity/QItem.java
  src/main/generated/site/bidderown/server/bounded_context/item/entity/QItemBase.java
  src/main/java/site/bidderown/server/base/base_entity/BaseEntity.java
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
  src/main/java/site/bidderown/server/bounded_context/comment/entity/Comment.java
  src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/ItemBase.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemJdbcRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/application-dev.yml
  src/main/resources/templates/usr/item/home.html
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: Test, Feature, Refactoring

#200 [#199] redis config
  .gitignore
  build.gradle
  src/main/java/site/bidderown/server/base/redis/EmbeddedRedisConfig.java
  src/main/java/site/bidderown/server/base/redis/ExpirationListener.java
  src/main/java/site/bidderown/server/base/redis/RedisConfig.java
  src/main/resources/application-db.yml.txt
  src/main/resources/application.yml
Labels: Setting, Refactoring

#204 [#201] 아이템 경매 종료 기간 redis로 처리
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/base/event/BidEndEvent.java
  src/main/java/site/bidderown/server/base/event/ItemCommentAlarmEvent.java
  src/main/java/site/bidderown/server/base/redis/EmbeddedRedisConfig.java
  src/main/java/site/bidderown/server/base/redis/ExpirationListener.java
  src/main/java/site/bidderown/server/base/redis/RedisConfig.java
  src/main/java/site/bidderown/server/batch/BatchScheduler.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
  src/main/java/site/bidderown/server/bounded_context/image/service/ImageService.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/event_handler/ItemEventHandler.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemExpirationQueueRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/java/site/bidderown/server/bounded_context/notification/entity/Notification.java
  src/main/java/site/bidderown/server/bounded_context/notification/event_handler/NotificationEventHandler.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: Feature, Refactoring

#206 [#205] 레디스 설정 및 테스트 코드
  src/main/resources/application-db.yml.txt
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: BugFix, Refactoring

#207 [#206] bugFix: redis-setting
  src/main/java/site/bidderown/server/base/redis/EmbeddedRedisConfig.java
  src/main/resources/application-db.yml.txt
  src/main/resources/application-test.yml
Labels: BugFix

#210 [#209] 레디스 환경 분리 및 테스트 코드 수정
  src/main/java/site/bidderown/server/base/redis/EmbeddedRedisConfig.java
  src/main/resources/application-test.yml
  src/test/java/site/bidderown/server/ServerApplicationTests.java
  src/test/java/site/bidderown/server/bounded_context/bid/controller/BidControllerTest.java
  src/test/java/site/bidderown/server/bounded_context/bid/service/BidServiceTest.java
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
  src/test/java/site/bidderown/server/bounded_context/notification/service/NotificationServiceTest.java
Labels: BugFix, Test, Setting, Refactoring

#216 [#215] 배포 환경 세팅
  src/main/java/site/bidderown/server/bounded_context/HomeController.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/ChatRoomController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/member/controller/MemberController.java
  src/main/resources/application-db.yml.txt
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: BugFix, Setting

#219 [#214] 댓글, 입찰 CQRS 패턴 적용
  src/main/generated/site/bidderown/server/bounded_context/item/entity/QItem.java
  src/main/generated/site/bidderown/server/bounded_context/item/entity/QItemBase.java
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/base/redis/ExpirationListener.java
  src/main/java/site/bidderown/server/base/redis/RedisConfig.java
  src/main/java/site/bidderown/server/base/scheduler/Scheduler.java
  src/main/java/site/bidderown/server/base/scheduler/SchedulerRunner.java
  src/main/java/site/bidderown/server/bounded_context/bid/repository/BidRepository.java
  src/main/java/site/bidderown/server/bounded_context/bid/service/BidService.java
  src/main/java/site/bidderown/server/bounded_context/comment/repository/CommentRepository.java
  src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/ItemBase.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemExpirationQueueRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRedisRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/scheduler/ItemCounterScheduler.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemRedisService.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/templates/usr/item/detail.html
  src/main/resources/templates/usr/item/home.html
  src/test/java/site/bidderown/server/bounded_context/bid/service/BidServiceTest.java
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
  src/test/java/site/bidderown/server/bounded_context/notification/service/NotificationServiceTest.java
Labels: BugFix, Setting, Feature, Refactoring

#222 [#221] redirect url 하드코딩 제거
  src/main/resources/templates/header.html
  src/main/resources/templates/usr/bid/list.html
  src/main/resources/templates/usr/chat/list.html
  src/main/resources/templates/usr/item/detail.html
  src/main/resources/templates/usr/item/home.html
  src/main/resources/templates/usr/notification/list.html
Labels: BugFix, Setting

#223 [#203] 좋아요 기능 추가
  src/main/generated/site/bidderown/server/bounded_context/heart/entity/QHeart.java
  src/main/generated/site/bidderown/server/bounded_context/item/entity/QItem.java
  src/main/java/site/bidderown/server/bounded_context/heart/controller/HeartApiController.java
  src/main/java/site/bidderown/server/bounded_context/heart/controller/dto/HeartResponse.java
  src/main/java/site/bidderown/server/bounded_context/heart/entity/Heart.java
  src/main/java/site/bidderown/server/bounded_context/heart/repository/HeartRepository.java
  src/main/java/site/bidderown/server/bounded_context/heart/service/HeartService.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRedisRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/scheduler/ItemCounterScheduler.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemRedisService.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/static/image/empty_heart.png
  src/main/resources/static/image/full_heart.png
  src/main/resources/templates/usr/item/detail.html
  src/main/resources/templates/usr/my_page.html
Labels: Feature

#225 [#224] S3Bucket도입
  build.gradle
  src/main/java/site/bidderown/server/base/resolver/PathResolver.java
  src/main/java/site/bidderown/server/base/s3bucket/NcpS3Config.java
  src/main/java/site/bidderown/server/base/util/ImageUtils.java
  src/main/java/site/bidderown/server/bounded_context/image/controller/ImageController.java
  src/main/java/site/bidderown/server/bounded_context/image/service/ImageService.java
  src/main/resources/images/item/abc.txt
  src/main/resources/images/item/banana.jpg
  src/main/resources/images/item/image1.jpeg
  src/main/resources/images/item/image10.jpeg
  src/main/resources/images/item/image11.jpeg
  src/main/resources/images/item/image2.jpeg
  src/main/resources/images/item/image3.jpeg
  src/main/resources/images/item/image4.jpeg
  src/main/resources/images/item/image5.jpeg
  src/main/resources/images/item/image6.jpeg
  src/main/resources/images/item/image7.jpeg
  src/main/resources/images/item/image8.jpeg
  src/main/resources/images/item/image9.jpeg
  src/main/resources/images/test/abc.txt
  src/main/resources/static/image/add_item.png
  src/main/resources/static/image/bidder_own_logo.png
  src/main/resources/static/image/chat.png
  src/main/resources/static/image/chat_noti.png
  src/main/resources/static/image/comment.png
  src/main/resources/static/image/empty_heart.png
  src/main/resources/static/image/full_heart.png
  src/main/resources/static/image/kakao_login.png
  src/main/resources/static/image/notification.png
  src/main/resources/static/image/notification_noti.png
  src/main/resources/static/image/person.png
  src/main/resources/static/image/person2.png
  src/main/resources/static/image/profile.png
  src/main/resources/static/image/submit.png
  src/main/resources/templates/header.html
  src/main/resources/templates/usr/bid/list.html
  src/main/resources/templates/usr/chat/list.html
  src/main/resources/templates/usr/form_login.html
  src/main/resources/templates/usr/item/detail.html
  src/main/resources/templates/usr/item/home.html
  src/main/resources/templates/usr/login.html
  src/main/resources/templates/usr/my_page.html
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: Setting, Refactoring

#230 [#202] 상품 수정하기
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemUpdateRequest.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemUpdateResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/templates/usr/item/create.html
  src/main/resources/templates/usr/item/update.html
  src/main/resources/templates/usr/my_page.html
Labels: Feature

#248 Setting/231 test api
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemCountFacade.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemRedisService.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: Setting, Refactoring

#254 댓글 N+1, Paging
  src/main/generated/site/bidderown/server/bounded_context/comment/controller/dto/QCommentDetailResponseV2.java
  src/main/java/site/bidderown/server/bounded_context/comment/controller/CommentApiController.java
  src/main/java/site/bidderown/server/bounded_context/comment/repository/CommentCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/comment/repository/CommentRepository.java
  src/main/java/site/bidderown/server/bounded_context/comment/service/CommentService.java
  src/main/resources/templates/usr/item/detail.html
  src/test/java/site/bidderown/server/bounded_context/comment/CommentServiceTest.java
Labels: Refactoring

#256 [#251] 레디스 count 감소 기능
  src/main/java/site/bidderown/server/base/redis/buffer/Buffer.java
  src/main/java/site/bidderown/server/base/redis/buffer/BufferTask.java
  src/main/java/site/bidderown/server/base/redis/buffer/CountBuffer.java
  src/main/java/site/bidderown/server/base/redis/buffer/CountTask.java
  src/main/java/site/bidderown/server/base/redis/buffer/CounterTaskType.java
  src/main/java/site/bidderown/server/bounded_context/bid/entitylistener/BidCountTask.java
  src/main/java/site/bidderown/server/bounded_context/bid/entitylistener/BidEntityListener.java
  src/main/java/site/bidderown/server/bounded_context/comment/entitylistener/CommentCountTask.java
  src/main/java/site/bidderown/server/bounded_context/comment/entitylistener/CommentEntityListener.java
  src/main/java/site/bidderown/server/bounded_context/heart/entitylistener/HeartCountTask.java
  src/main/java/site/bidderown/server/bounded_context/heart/entitylistener/HeartEntityListener.java
  src/main/java/site/bidderown/server/bounded_context/item/buffer/ItemCountBuffer.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRedisRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/scheduler/ItemCountScheduler.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemRedisService.java
Labels: Feature

#257 [#255] CQRS 패턴 적용 안된 Item detail api 추가
  src/main/java/site/bidderown/server/bounded_context/comment/controller/dto/CommentDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemDetailResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
Labels: Feature

#259 [#238] 아이템 리스트, 디테일 쿼리 튜닝 및 테스트 api
  src/main/java/site/bidderown/server/ServerApplication.java
  src/main/java/site/bidderown/server/base/data/NotProd.java
  src/main/java/site/bidderown/server/batch/BatchScheduler.java
  src/main/java/site/bidderown/server/batch/item/config/ItemJobConfiguration.java
  src/main/java/site/bidderown/server/batch/item/listener/BidEndJobListener.java
  src/main/java/site/bidderown/server/batch/item/listener/BidEndNotificationWriterListener.java
  src/main/java/site/bidderown/server/batch/item/listener/BidEndWriterListener.java
  src/main/java/site/bidderown/server/bounded_context/comment/repository/CommentCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemRedisService.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/application-dev.yml
  src/main/resources/templates/usr/item/detail.html
Labels: Setting, Feature, Refactoring

#264 [#263] 상품 상세 ui 리팩토링
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/java/site/bidderown/server/bounded_context/member/controller/MemberController.java
  src/main/resources/templates/header.html
  src/main/resources/templates/usr/item/detail.html
  src/main/resources/templates/usr/item/home.html
Labels: BugFix, Refactoring

#270 [#266] 상품 등록, 마이페이지 리팩토링
  src/main/resources/templates/import.html
  src/main/resources/templates/usr/item/create.html
  src/main/resources/templates/usr/my_page.html
Labels: Refactoring

#273 UI수정
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemController.java
  src/main/resources/templates/header.html
  src/main/resources/templates/usr/item/bid_list.html
  src/main/resources/templates/usr/item/heart_list.html
  src/main/resources/templates/usr/item/home.html
  src/main/resources/templates/usr/item/sale_list.html
  src/main/resources/templates/usr/my_page.html
  src/main/resources/templates/usr/notification/list.html
Labels: BugFix, Feature

#274 [#269] chat UI
  src/main/generated/site/bidderown/server/bounded_context/comment/controller/dto/QCommentDetailResponseV2.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomDetail.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/controller/dto/ChatRoomResponse.java
  src/main/java/site/bidderown/server/bounded_context/chat_room/service/ChatRoomService.java
  src/main/resources/templates/usr/chatroom/list.html
  src/main/resources/templates/usr/item/detail.html
  src/main/resources/templates/usr/item/home.html
  src/main/resources/templates/usr/notification/list.html
Labels: Refactoring

#277 feature/bidding-filter-추가
  src/main/java/site/bidderown/server/bounded_context/bid/controller/BidController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsRequest.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/templates/header.html
  src/main/resources/templates/usr/bid/list.html
  src/main/resources/templates/usr/item/create.html
  src/main/resources/templates/usr/item/home.html
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: Feature

#279 [#242] README.md 파일 추가
  README.md
Labels: Document

#280 23.07.18
  README.md
  src/main/java/site/bidderown/server/bounded_context/bid/controller/BidController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsRequest.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/templates/header.html
  src/main/resources/templates/usr/bid/list.html
  src/main/resources/templates/usr/item/create.html
  src/main/resources/templates/usr/item/home.html
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: Refactoring, Document

#283 readme파일 수정
  README.md
Labels: Document

#282 [#281]입찰 알림 창 UI수정
  src/main/resources/templates/import.html
  src/main/resources/templates/usr/item/create.html
  src/main/resources/templates/usr/item/detail.html
Labels: Refactoring

#293 [#292] 경매 종료 순 커버링 인덱스 적용
  src/main/java/site/bidderown/server/bounded_context/bid/repository/BidRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/test/java/site/bidderown/server/bounded_context/item/Controller/ItemControllerTest.java
Labels: Feature

#295 [#294] 인기도 순 쿼리 개선
  src/main/java/site/bidderown/server/ServerApplication.java
  src/main/java/site/bidderown/server/base/base_entity/BaseEntity.java
  src/main/java/site/bidderown/server/base/redis/listener/ExpirationListener.java
  src/main/java/site/bidderown/server/bounded_context/bid/entity/Bid.java
  src/main/java/site/bidderown/server/bounded_context/bid/entitylistener/BidEntityListener.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/ItemApiController.java
  src/main/java/site/bidderown/server/bounded_context/item/controller/dto/ItemsResponse.java
  src/main/java/site/bidderown/server/bounded_context/item/entity/Item.java
  src/main/java/site/bidderown/server/bounded_context/item/entitylistener/ItemEntityListener.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemCustomRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/repository/ItemRedisRepository.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemRedisService.java
  src/main/java/site/bidderown/server/bounded_context/item/service/ItemService.java
  src/main/resources/application.yml
  src/test/java/site/bidderown/server/bounded_context/item/service/ItemServiceTest.java
Labels: Feature, Refactoring
